using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System.Text;

namespace Dhazel.Revertibles.Generators;

[Generator(LanguageNames.CSharp)]
public class RevertibleObjectGenerator : IIncrementalGenerator
{
    private const string AttributeFullName = "Dhazel.Revertibles.RevertibleObjectAttribute";

    private record struct Model(
        string Namespace,
        string ClassName,
        string FullTypeName,
        bool IsPartial);

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var candidates = context.SyntaxProvider.ForAttributeWithMetadataName(
            AttributeFullName,
            predicate: static (node, _) => node is ClassDeclarationSyntax,
            transform: static (ctx, _) => Transform(ctx));

        context.RegisterSourceOutput(candidates, static (spc, model) =>
        {
            if (model is null) return;
            spc.AddSource($"{model.Value.FullTypeName}.RevertibleObject.g.cs", Generate(model.Value));
        });
    }

    private static Model? Transform(GeneratorAttributeSyntaxContext ctx)
    {
        var classSymbol = (INamedTypeSymbol)ctx.TargetSymbol;
        var classSyntax = (ClassDeclarationSyntax)ctx.TargetNode;

        var isPartial = classSyntax.Modifiers.Any(SyntaxKind.PartialKeyword);

        return new Model(
            Namespace: classSymbol.ContainingNamespace.IsGlobalNamespace
                ? string.Empty
                : classSymbol.ContainingNamespace.ToDisplayString(),
            ClassName: classSymbol.Name,
            FullTypeName: classSymbol.ToDisplayString(),
            IsPartial: isPartial);
    }

    private static SourceText Generate(Model model)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        if (!model.IsPartial)
        {
            sb.AppendLine($"// {model.ClassName} must be declared 'partial' for RevertibleObject codegen to apply.");
            return SourceText.From(sb.ToString(), Encoding.UTF8);
        }

        var hasNamespace = !string.IsNullOrEmpty(model.Namespace);
        if (hasNamespace)
        {
            sb.AppendLine($"namespace {model.Namespace};");
            sb.AppendLine();
        }

        sb.AppendLine($$"""
            partial class {{model.ClassName}}
            {
                private global::Dhazel.Revertibles.Revertible? __revertible;

                private global::Dhazel.Revertibles.IRevertible __Revertible =>
                    __revertible ??= new global::Dhazel.Revertibles.Revertible(this, false);

                /// <inheritdoc cref="global::Dhazel.Revertibles.IRevertible.AcceptChanges"/>
                public void AcceptChanges(string? propertyName = null) => __Revertible.AcceptChanges(propertyName);

                /// <inheritdoc cref="global::Dhazel.Revertibles.IRevertible.HasChanged"/>
                public bool HasChanged(string? propertyName = null) => __Revertible.HasChanged(propertyName);

                /// <inheritdoc cref="global::Dhazel.Revertibles.IRevertible.Revert"/>
                public void Revert(string? propertyName = null) => __Revertible.Revert(propertyName);

                /// <inheritdoc cref="global::Dhazel.Revertibles.IRevertible.WithProperties"/>
                public global::Dhazel.Revertibles.IRevertible WithProperties(System.Collections.Generic.List<string> propertyNames)
                {
                    __Revertible.WithProperties(propertyNames);
                    return __Revertible;
                }
            }
            """);

        return SourceText.From(sb.ToString(), Encoding.UTF8);
    }
}